name: popsicle_example
description: Popsicle example app.
publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  popsicle:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
